# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('leo-satellite', ['core', 'mobility', 'network'])
    module.source = [
        'model/leo-satellite-config.cc',
        'model/leo-channel.cc',
        'model/mobility/leo-satellite-mobility.cc',
        'model/mobility/orbit-position-allocator.cc',
        'helper/leo-satellite-helper.cc',
        
        ]

    module_test = bld.create_ns3_module_test_library('leo-satellite')
    module_test.source = [
        'test/leo-satellite-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'leo-satellite'
    headers.source = [
        'model/leo-satellite-config.h',
        'model/leo-channel.h',
        'model/mobility/leo-satellite-mobility.h',
        'model/mobility/orbit-position-allocator.h',
        'helper/leo-satellite-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

